name: Build UWP Benchmark App

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore AppLaunchRnd.sln

    - name: Build UWP App
      run: >
        msbuild AppLaunchRnd\AppLaunchRnd.csproj
        /p:Configuration=Release
        /p:Platform=x64
        /p:UseDotNetNativeToolchain=true
        /p:UapAppxPackageBuildMode=SideloadOnly
        /p:AppxBundle=Always
        /p:AppxBundlePlatforms="x64"
        /p:AppxPackageSigningEnabled=true
        /p:PackageCertificateKeyFile=TemporaryKey.pfx
        /p:PackageCertificatePassword=password
        /p:GenerateAppInstallerFile=false

    - name: Upload MSIX Bundle
      uses: actions/upload-artifact@v4
      with:
        name: UWP-Benchmark-App
        path: AppLaunchRnd\AppPackages\
