name: Build UWP Benchmark App

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore AppLaunchRnd.sln

    - name: Build UWP App
      run: >
        msbuild AppLaunchRnd\AppLaunchRnd.csproj
        /p:Configuration=Release
        /p:Platform=x64
        /p:AppxPackageSigningEnabled=false
        /p:UseDotNetNativeToolchain=false
        /p:AppxBundle=Never

    - name: Upload UWP Build Output
      uses: actions/upload-artifact@v4
      with:
        name: UWP-Benchmark-App
        path: AppLaunchRnd\bin\x64\Release\
